name: ci/cd-pipeline

on:
  push:
    branches: 
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Setup DOTNET
        uses: actions/checkout@v3

      - name: Setup .Net
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with .NET
        shell: cmd
        run: |
          cd DigitalSignature
          dotnet build --configuration Release
      
      - name: Publish .NET
        shell: cmd
        run: |
          dotnet publish -c Release -o .\myapp

      - name: Deploy to IIS
        shell: cmd
        run: |
          iisreset /stop
          xcopy /s /y .\myapp\* C:\www\digitalsignature_app
          iisreset /start
          
